<?php

namespace AppBundle\Entity;

/**
 * Blog2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Blog2Repository extends \Doctrine\ORM\EntityRepository
{
}
